---
kubeadm_config_file: /etc/kubernetes/kubeadm.yml
kubelet_config_path: /var/lib/kubelet/kubelet-config
kubernetes_control_plane_address: "{{ ansible_fqdn }}"
kubernetes_bootstrap_token: ""
kubernetes_ca_hash: ""
# cloud-provider flag removed from kube-apiserver in K8s v1.33+
# Still used by kube-controller-manager and kubelet, also in kube-apiserver in supported versions 1.31 and 1.32
kubernetes_cloud_provider: ""
kubernetes_hostname: "{{ ansible_fqdn }}"
kubernetes_role: "worker"
kubernetes_taints: []
kubelet_config_streaming_connection_idle_timeout: "5m"
kubelet_config_read_only_port: 0

kubelet_config_server_tls_bootstrap: true

# kubelet_config_tls_cert_file: /var/lib/kubelet/pki/kubelet.crt
# kubelet_config_tls_private_key_file: /var/lib/kubelet/pki/kubelet.key
kubelet_certificate_authority_file: /etc/kubernetes/pki/ca.crt
kubelet_config_pod_pids_limit: 4096

## Encryption
tls_cipher_suites:
  - TLS_AES_128_GCM_SHA256
  - TLS_AES_256_GCM_SHA384
  - TLS_CHACHA20_POLY1305_SHA256
  - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
  - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
  - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
  - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256
  - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
  - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
  - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
  - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256

kubelet_tls_cipher_suites:
  - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
  - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
  - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
  - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
  - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
  - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
