---
argument_specs:
  main:
    short_description: "Kubernetes control plane setup"
    options:
      kubernetes_kube_proxy_mode:
        type: str
        required: false
        default: ipvs
        choices:
          - ipvs
          - nftables
        description: "kube-proxy operating mode"
