---
kubeadm_config_file: /etc/kubernetes/kubeadm.yml
kubeadm_upgrade_config_file: /etc/kubernetes/kubeadm-upgrade-config.yml
kubeadm_patches_path: /etc/kubernetes/patches/
kubeadm_config_path: /etc/kubernetes/kubeadm-config
kubeadm_skip_phases: []
kubelet_config_path: /var/lib/kubelet/kubelet-config
audit_log_dir: /var/log/kubernetes
audit_policy_max_age: 3
audit_policy_config_path: /etc/kubernetes/audit.yaml

## MasterConfig paramethers
kubernetes_apiserver_advertise_address: "{{ ansible_default_ipv4.address }}"
kubernetes_pod_cidr: "10.32.0.0/16"
kubernetes_svc_cidr: "10.96.0.0/16"
kubernetes_cluster_name: "sighup-prod"
# cloud-provider flag removed from kube-apiserver in K8s v1.33+
# Still used by kube-controller-manager and kubelet; also in kube-apiserver in supported versions 1.31 and 1.32
kubernetes_cloud_provider: ""
# cloud-config flag removed from kube-apiserver in K8s v1.33+
kubernetes_cloud_config: ""
# Use kubernetes_apiserver_certSANs to set extra alternative names in the API Server signing certificate
# Accepts a list of strings, in which each string can be either an IP Address or a domain
kubernetes_apiserver_certSANs: []
kubernetes_control_plane_address: "{{ ansible_hostname }}"
kubernetes_version: "1.33.4"
kubernetes_image_registry: "{{ dependencies[kubernetes_version].kubernetes_image_registry }}"
coredns_image_prefix: "{{ dependencies[kubernetes_version].coredns_image_prefix | default('/coredns') }}"
kubernetes_hostname: "{{ ansible_fqdn }}"
kubernetes_kubeconfig_path: "."
kubernetes_users_names: []
kubernetes_users_org: sighup
kubernetes_users_kubeconfig_dir: /etc/kubernetes/users
kubernetes_encryption_config: ""
kubernetes_remote_encryption_config: "/etc/kubernetes/encryption-config.yml"

etcd:
  endpoints:
    - "https://127.0.0.1:2379"
  caFile: "/etc/etcd/pki/etcd/ca.crt"
  keyFile: "/etc/etcd/pki/apiserver-etcd-client.key"
  certFile: "/etc/etcd/pki/apiserver-etcd-client.crt"

## OIDC
oidc_issuer_url: ""
oidc_client_id: ""
oidc_ca_file: /etc/ssl/certs/ca-certificates.crt
oidc_username_claim: email
oidc_username_prefix: "oidc:"
oidc_groups_claim: groups
oidc_groups_prefix: "oidc:"

upgrade: False

dependencies:
  # To pin dependencies for each Kubernetes version
  "1.28.7":
    kubernetes_image_registry: "registry.sighup.io/fury/on-premises"
  "1.28.15":
    kubernetes_image_registry: "registry.sighup.io/fury/on-premises"
  "1.29.3":
    kubernetes_image_registry: "registry.sighup.io/fury/on-premises"
  "1.29.10":
    kubernetes_image_registry: "registry.sighup.io/fury/on-premises"
  "1.30.6":
    kubernetes_image_registry: "registry.sighup.io/fury/on-premises"
  "1.30.11":
    kubernetes_image_registry: "registry.sighup.io/fury/on-premises"
  "1.31.4":
    kubernetes_image_registry: "registry.sighup.io/fury/on-premises"
  "1.31.7":
    kubernetes_image_registry: "registry.sighup.io/fury/on-premises"
  "1.31.12":
    kubernetes_image_registry: "registry.sighup.io/fury/on-premises"
  "1.32.3":
    kubernetes_image_registry: "registry.sighup.io/fury/on-premises"
  "1.32.4":
    kubernetes_image_registry: "registry.sighup.io/fury/on-premises"
  "1.32.8":
    kubernetes_image_registry: "registry.sighup.io/fury/on-premises"
  "1.33.4":
    kubernetes_image_registry: "registry.sighup.io/fury/on-premises"

## Controller Manager
terminated_pod_gc_threshold: 500

## Admission plugins
eventratelimits:
  - type: Server
    qps: 500
    burst: 2000
  - type: Namespace
    qps: 20
    burst: 100
    cacheSize: 4096
  - type: User
    qps: 20
    burst: 100
    cacheSize: 4096

## Kubelet
kubelet_config_streaming_connection_idle_timeout: "5m"
kubelet_config_read_only_port: 0
kubelet_config_server_tls_bootstrap: true
# kubelet_config_tls_cert_file: /var/lib/kubelet/pki/kubelet.crt
# kubelet_config_tls_private_key_file: /var/lib/kubelet/pki/kubelet.key
kubelet_certificate_authority_file: /etc/kubernetes/pki/ca.crt
kubelet_config_pod_pids_limit: 4096

## Encryption
tls_cipher_suites:
  - TLS_AES_128_GCM_SHA256
  - TLS_AES_256_GCM_SHA384
  - TLS_CHACHA20_POLY1305_SHA256
  - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
  - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
  - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
  - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256
  - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
  - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
  - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
  - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256

kubelet_tls_cipher_suites:
  - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
  - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
  - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
  - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
  - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
  - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
