apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: csr-auto-approver
rules:
- apiGroups: ["certificates.k8s.io"]
  resources:
    - certificatesigningrequests
    - certificatesigningrequests/approval 
  verbs: ["get", "list", "watch", "update", "patch"]
- apiGroups: ["certificates.k8s.io"]
  resources: ["signers"]
  resourceNames: ["kubernetes.io/kubelet-serving"]
  verbs: ["approve"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list"]